### ISSUE TITLE
Better WS Retry Logic

### ISSUE THREAD

**Issue by ratankaliani** [succinctlabs/vectorx#117]
If the WS connection closes, how & where should we re-initialize the connection?

**Comment by prabal-banerjee** [comment]
You use `subxt` for connection?

**Comment by ratankaliani** [comment]
Yes the re-exposed `subxt-rpc` crate.

**Comment by prabal-banerjee** [comment]
These improvements might be helpful. 

https://github.com/paritytech/subxt/issues/1190#issuecomment-1936182064
https://github.com/paritytech/subxt/pull/1396

**Comment by ratankaliani** [comment]
Oh nice, that looks great, thanks for pointing it out @prabal-banerjee!
